server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/identity_service
#    username: root
#    password: 182003

    # Sửa Host, Port và tên database (demo_db) cho đúng với Aiven của bạn
    url:jdbc:mysql://mim-demo-khuongcuong59-cc8f.b.aivencloud.com:10069/mim_db
    username:avnadmin
    password:AVNS_ao75-zJeGMASbxHYHWI

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


jwt:
  sharedKey: "m6eR6XpkVVfX+fubIUPxv0HsbJ7uox9xOUimZZMUigM="
